version: '3'

volumes:
  dm_data:
    external: false


services:
  backend:
    image: "${BACKEND_IMAGE}:${BACKEND_IMAGE_TAG}"
    expose:
      - 5000
    env_file: backend/.env
    depends_on:
      - redis
      - db
    volumes:
      - ./backend:/code
    restart: always
    command: "python app.py"

  worker:
    image: "${BACKEND_IMAGE}:${BACKEND_IMAGE_TAG}"
    env_file: backend/.env
    volumes:
      - ./backend:/code
    depends_on:
      - backend
      - redis
      - db
    command: "celery -A app.celery  worker -l info"

  redis:
    image: "redis:5.0.1-alpine"
    restart: always

  db:
    image: 'postgres:10.10-alpine'
    volumes:
      - dm_data:/var/lib/postgresql/data
    env_file: backend/.env

  frontend:
      image: "${FRONTEND_IMAGE}:${FRONTEND_IMAGE_TAG}"
      restart: always
      ports:
        - 80:80
      depends_on:
        - backend
