services:
  backend:
    command: python app.py
    depends_on:
    - db
    - redis
    environment:
      APP_SETTINGS: config.ProductionConfig
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CLIENT_ID: dbf8415f4c37452944c7
      CLIENT_SECRET: 7b985c27c56528cdfb6a51dfcd0f57cf204836b8
      DATABASE_URL: postgresql://dm_admin:dm_pwd@db:5432/dm_db
      GITHUB_WEBHOOKS_SECRET: webhookpass
      HOST: localhost
      OAUTHLIB_INSECURE_TRANSPORT: '1'
      POSTGRES_DB: dm_db
      POSTGRES_PASSWORD: dm_pwd
      POSTGRES_PORT: '5432'
      POSTGRES_USER: dm_admin
      REDIRECT_URL: http://127.0.0.1:5000/github_login
    expose:
    - 5000
    image: sigmaproit/dependency-manager-be:latest
    restart: always
    volumes:
    - /home/shehab/work/dependency-manager/dependency-manager-compose/backend:/code:rw
  db:
    environment:
      APP_SETTINGS: config.ProductionConfig
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CLIENT_ID: dbf8415f4c37452944c7
      CLIENT_SECRET: 7b985c27c56528cdfb6a51dfcd0f57cf204836b8
      DATABASE_URL: postgresql://dm_admin:dm_pwd@db:5432/dm_db
      GITHUB_WEBHOOKS_SECRET: webhookpass
      HOST: localhost
      OAUTHLIB_INSECURE_TRANSPORT: '1'
      POSTGRES_DB: dm_db
      POSTGRES_PASSWORD: dm_pwd
      POSTGRES_PORT: '5432'
      POSTGRES_USER: dm_admin
      REDIRECT_URL: http://127.0.0.1:5000/github_login
    image: postgres:10.10-alpine
    volumes:
    - dm_data:/var/lib/postgresql/data:rw
  frontend:
    depends_on:
    - backend
    image: sigmaproit/dependency-manager-frontend:latest
    ports:
    - 80:80/tcp
    restart: always
  redis:
    image: redis:5.0.1-alpine
    restart: always
  worker:
    command: celery -A app.celery  worker -l info
    depends_on:
    - backend
    - db
    - redis
    environment:
      APP_SETTINGS: config.ProductionConfig
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CLIENT_ID: dbf8415f4c37452944c7
      CLIENT_SECRET: 7b985c27c56528cdfb6a51dfcd0f57cf204836b8
      DATABASE_URL: postgresql://dm_admin:dm_pwd@db:5432/dm_db
      GITHUB_WEBHOOKS_SECRET: webhookpass
      HOST: localhost
      OAUTHLIB_INSECURE_TRANSPORT: '1'
      POSTGRES_DB: dm_db
      POSTGRES_PASSWORD: dm_pwd
      POSTGRES_PORT: '5432'
      POSTGRES_USER: dm_admin
      REDIRECT_URL: http://127.0.0.1:5000/github_login
    image: sigmaproit/dependency-manager-be:latest
    volumes:
    - /home/shehab/work/dependency-manager/dependency-manager-compose/backend:/code:rw
version: '3.0'
volumes:
  dm_data:
    external: false

