apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
      - args:
        - celery
        - -A
        - app.celery
        - worker
        - -l
        - info
        env:
        - name: APP_SETTINGS
          valueFrom:
            configMapKeyRef:
              key: APP_SETTINGS
              name: worker-backend--env
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              key: CELERY_BROKER_URL
              name: worker-backend--env
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              key: CELERY_RESULT_BACKEND
              name: worker-backend--env
        - name: CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: CLIENT_ID
              name: worker-backend--env
        - name: CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              key: CLIENT_SECRET
              name: worker-backend--env
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: worker-backend--env
        - name: GITHUB_WEBHOOKS_SECRET
          valueFrom:
            configMapKeyRef:
              key: GITHUB_WEBHOOKS_SECRET
              name: worker-backend--env
        - name: HOST
          valueFrom:
            configMapKeyRef:
              key: HOST
              name: worker-backend--env
        - name: OAUTHLIB_INSECURE_TRANSPORT
          valueFrom:
            configMapKeyRef:
              key: OAUTHLIB_INSECURE_TRANSPORT
              name: worker-backend--env
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: worker-backend--env
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: worker-backend--env
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PORT
              name: worker-backend--env
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: worker-backend--env
        - name: REDIRECT_URL
          valueFrom:
            configMapKeyRef:
              key: REDIRECT_URL
              name: worker-backend--env
        image: {{ .Values.backend.image }}:{{ .Values.backend.imageTag }}
        name: worker
        resources: {}
        volumeMounts:
        - mountPath: /code
          name: worker-claim0
      restartPolicy: Always
      volumes:
      - name: worker-claim0
        persistentVolumeClaim:
          claimName: worker-claim0
status: {}
