"""empty message

Revision ID: 3ae21cfd45f5
Revises: 
Create Date: 2019-07-24 17:26:54.855186

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3ae21cfd45f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('url', sa.String(length=512), nullable=False),
                    sa.Column('avatar_url', sa.String(length=512), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=True),
                    sa.Column('login', sa.String(length=80), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('bio', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('avatar_url'),
                    sa.UniqueConstraint('bio'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('login'),
                    sa.UniqueConstraint('url')
                    )
    op.create_table('repo',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=150), nullable=False),
                    sa.Column('full_name', sa.String(length=255), nullable=False),
                    sa.Column('url', sa.String(length=512), nullable=False),
                    sa.Column('default_branch', sa.String(length=52), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('update_at', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('full_name'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('url')
                    )
    op.create_table('token',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('token', sa.String(length=40), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('token')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.drop_table('repo')
    op.drop_table('user')
    # ### end Alembic commands ###
