"""empty message

Revision ID: 409f0cee884e
Revises: bf266bff44f2
Create Date: 2019-09-08 16:10:43.075851

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '409f0cee884e'
down_revision = 'bf266bff44f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo', sa.Column('repo_api_url', sa.String(), nullable=True))
    op.add_column('user', sa.Column('user_api_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_api_url')
    op.drop_column('repo', 'repo_api_url')
    # ### end Alembic commands ###
