"""empty message

Revision ID: bf266bff44f2
Revises: cb5bd30bfdef
Create Date: 2019-07-29 18:25:50.555795

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bf266bff44f2'
down_revision = 'cb5bd30bfdef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_dependency',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('repo_id', sa.Integer(), nullable=True),
                    sa.Column('depending_on_repo_id', sa.Integer(), nullable=True),
                    sa.Column('api_url', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['depending_on_repo_id'], ['repo.id'], ),
                    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_dependency')
    # ### end Alembic commands ###
