"""empty message

Revision ID: cb5bd30bfdef
Revises: 3ae21cfd45f5
Create Date: 2019-07-28 19:02:43.897112

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb5bd30bfdef'
down_revision = '3ae21cfd45f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo', sa.Column('repo_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo', 'repo_data')
    # ### end Alembic commands ###
